### ISSUE TITLE
HttpNotFoundException

### ISSUE THREAD

**Issue by alaglil** [maurobonfietti/slim4-soccer-api-demo#1]
I have error : 

{
    "message": "Not found.",
    "class": "HttpNotFoundException",
    "status": "error",
    "code": 404
}

Get : http://php7.test/slim4-soccer-api-demo/public/hello/im

Routes.php
```

<?php declare(strict_types=1);

$app->get('/hello/{name}', function () {
    return 'hellol';
   });
```

**Comment by maurobonfietti** [comment]
Hello @alaglil !

Try something like this:

Routes.php

```php
<?php declare(strict_types=1);

$app->get('/hello/{name}', function ($request, $response, array $args) {
    $message = "Hello " . $args['name'];
    $response->getBody()->write($message);
    $response->withStatus(200);

    return $response;
});
```

I'm using PHP Built-in web server. So, I run this example with:

```bash
php -S 0.0.0.0:8080 -t public public/index.php
```

Request:

```
http://localhost:8080/hello/mnb
```
Response:
```
Hello mnb
```

<img width="473" alt="Captura de Pantalla 2020-03-06 a la(s) 10 51 04" src="https://user-images.githubusercontent.com/24535949/76089479-80df3180-5f98-11ea-8b1b-0bd343ad511a.png">


<img width="878" alt="Captura de Pantalla 2020-03-06 a la(s) 10 46 20" src="https://user-images.githubusercontent.com/24535949/76089329-32319780-5f98-11ea-97f1-3469d6a34629.png">


((Also, check your URL, maybe removing the "/public/" part.))

**Comment by alaglil** [comment]
Hello  ,

Thank you for your reliability and for building such nice slim api,
since I have a vm I just add $app->setBasePath('/slim4-soccer-api-demo/public'); 
waiting to migrate of /rest-api-slim-php to v4 
Thanks a lot

**Comment by maurobonfietti** [comment]
Fantastic!
Yes, I will add a feature to allow the setBasePath().
(Sometime, I'm also thinking to migrate rest-api-slim-php to v4 :-)
Thanks for your message.
Best Regards.
